import PageWrapper from "../_components/PageWrapper";

export const metadata = {
  title: "Page Wrapepr",
  description: "Generated by Next.js",
};

export default async function PageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <PageWrapper>{children}</PageWrapper>;
}
