import clsx from "clsx";
import "../styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "min-h-screen",
          "flex",
          "flex-col",
          "items-stretch",
          "justify-start"
        )}
      >
        {children}
      </body>
    </html>
  );
}
