import Header from "../_components/Header";
import { SiteInfoQueryRizzult } from "../_types";
import { SITE_INFO_QUERY } from "@/sanity/queries";
import Footer from "../_components/Footer";
import { sanityFetch } from "@/sanity/lib/client";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function BlogLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const siteInfo = await sanityFetch<SiteInfoQueryRizzult>({
    query: SITE_INFO_QUERY,
  });

  const { title, resume, socialMedia } = siteInfo[0];

  return (
    <>
      <Header title={title} />
      <main className="flex-1 container">{children}</main>
      <Footer resume={resume} socialMedia={socialMedia} />
    </>
  );
}
